# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20160226_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sektionsüberschrift'),
        ),
    ]
