# Generated by Django 2.1.15 on 2020-04-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20190918_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section_heading',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sektionsüberschrift'),
        ),
    ]
