# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-15 12:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('newsletter', '0004_article_section_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_newsletter_articles', to='filer.Image', verbose_name='Teaserbild'),
        ),
    ]
