# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_article_teaser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
    ]
