# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20180502_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser_copyright',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bild Copyright'),
        ),
    ]
