# Generated by Django 2.1.15 on 2020-04-18 15:25

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('newsletter', '0006_article_section_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_newsletter_articles', to=settings.FILER_IMAGE_MODEL, verbose_name='Teaserbild'),
        ),
    ]
