# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-30 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_article_teaser_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='teaser_copyright',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bildunterschrift'),
        ),
    ]
